wandb:
  activate: False
  project: ""
  entity: ""

current_model:
  save_model: True
  model_dir: "models_h5"
  model_name: "SpectroViTNew"

reload_from_existing_model:
  activate: False
  model_dir: "models_h5"
  model_name: "SpectroViTReload"

epochs: 44

optimizer:
  Adam:
    lr: 0.0001

loss: RangeMAELoss

lr_scheduler:
  activate: False
  scheduler_type: "cosineannealinglr"
  info:
    T_max: 10
    eta_min: 0.000001

model: SpectroViT

train:
  batch_size: 100
  num_workers: 4

valid:
  batch_size: 200
  num_workers: 4

train_dataset:
  DatasetThreeChannelSpectrogram:
    path_data: "data/train"
    validation: False
    random_augment:
      amplitude:
        noise_level_base:
          max: 3
          min: 0
        noise_level_scan_var:
          max: 3
          min: 0
      frequency:
        noise_level_base:
          max: 3
          min: 0
        noise_level_scan_var:
          max: 3
          min: 0
      phase:
        noise_level_base:
          max: 3
          min: 0
        noise_level_scan_var:
          max: 3
          min: 0

valid_dataset:
  DatasetThreeChannelSpectrogram:
    path_data: "data/val"
    validation: True

valid_on_the_fly:
  activate: True
  save_dir_path: "valid_on_the_fly"